### ISSUE TITLE
G_CLEF string should escape the slashes

### ISSUE THREAD

**Issue by ssilverman** [leadpony/jsonp-test-suite#6]
https://github.com/leadpony/jsonp-test-suite/blob/5efa9962d5a0452a00e8a2b2546b541991be5190/src/main/java/org/leadpony/jsonp/testsuite/tests/JsonValueTestCase.java#L58

I believe the string should be `"\\ud834\\udd1e\"`. i.e. escape the slashes because all the other test cases do.

**Comment by leadpony** [comment]
@ssilverman 
The Reference Implementation does not escape the G clef character (code point: U+1D11E), which belongs to the `unescaped` range `%x5D-10FFFF` defined in [RFC 7159](https://tools.ietf.org/html/rfc7159#section-7).

**Comment by leadpony** [comment]
More discussion continues at #4 .
