### ISSUE TITLE
thrown.getMessage() should first check if thrown is null

### ISSUE THREAD

**Issue by ssilverman** [leadpony/jsonp-test-suite#7]
There are a number of places where `thrown` is retrieved from the test and then `thrown.getMessage()` is called. These places should first check for `thrown == null` to avoid a possible `NullPointerException`; these cases will result in a test error but should instead result in a failure.

**Comment by ssilverman** [comment]
Example fix:
```java
doSomethingWith(thrown.getMessage());
```

becomes:
```java
assertThat(thrown).isNotNull();
doSomethingWith(thrown.getMessage());
```

**Comment by leadpony** [comment]
@ssilverman 
You are right. Could you write a PR for me?
